#!/usr/bin/env bash

source $(dirname `readlink -f $0`)/iv_scripts/config

join() {
  if [ -z $1 ] ; then
    echo "must provide a server URL to join"
    exit 50
  fi

  local port=$(config port)
  local location=$(config location)
  local user=$(config user)

  server new $1 ${2:-$port} ${3:-$location} ${4:-$user}
}

server() {
  $(dirname `readlink -f $0`)/iv_scripts/server $@
}

channel() {
  $(dirname `readlink -f $0`)/iv_scripts/channel $@
}

init() {
  mkdir -p $(config location)
  mkdir -p $(config bin_path)
  mkdir -p $(config log_path)
  mkdir -p $(config pid_path)
}

help() {
  cat <<HERE
iv -- a suite of helper scripts for ii

USAGE:

iv help              -- print this message
iv join <server url> -- join selected server on default port

HERE
}
alias 'usage'=help

_check_dependencies
_check_config
init
$@
