#!/usr/bin/env bash

source $(dirname `readlink -f $0`)/iv_base

_input() {
  echo "$@" > $(_ii_path)/$IV_CHANNEL_NAME/in
}

new() {
  local server=$1
  local channel=${2###}

  $server "_input" "/join #$channel"

  echo "IV_SERVER_NAME=$server IV_CHANNEL_NAME='#$channel' iv_channel \$@" > $(_bin_path $channel)
  chmod a+x $(_bin_path $channel)
}

watch() {
  tail -f $(_ii_path)/$IV_CHANNEL_NAME/out
}

say() {
  _input $@
}

part() {
  _input '/part'
  #TODO: Archive the data instead of just removing it
  rm -rf $(_ii_path)/$IV_CHANNEL_NAME
}

$@
