#!/usr/bin/env bash

source $(dirname `readlink -f $0`)/base

_input() {
  echo "$@" > $(_ii_path)/$IV_CHANNEL_NAME/in
}

new() {
  local server=$1
  local channel=${2###}

  $server _input /j "#$channel"

  echo "IV_SERVER_NAME=$server IV_CHANNEL_NAME='#$channel' iv channel \$@" > $(_bin_path $channel)
  chmod a+x $(_bin_path $channel)
  # ii doesn't build the outfile till it's needed, I need it immediately, so
  # I'll just touch it

  mkdir -p $(_ii_path)/\#$channel
  touch $(_ii_path)/\#$channel/out
}

watch() {
  tail -f $(_ii_path)/$IV_CHANNEL_NAME/out
}

say() {
  _input $@
}

part() {
  _input '/l'
  #TODO: Archive the data instead of just removing it
  rm -rf "$(_ii_path)/#${IV_CHANNEL_NAME###}/"
  #XXX: This is a bit abusive, since base directly references $IV_SERVER_NAME
  rm -rf "$(_bin_path ${IV_CHANNEL_NAME###})/"
}

$@
